language: python
python:
        - "2.7"
        - "3.6"
install:
        - pip install flake8
script:
        - python -m unittest discover        
matrix:
        include:
                - python: "3.6"
                  script: "flake8"        
